spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dotty
    username: dev
    password: fyrgag-tehpe6-Jitkox
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.tradingbot.dotty: WARN

server:
  port: 443
  ssl:
    key-store: keystore.p12
    key-store-password: dotty!
    keyStoreType: PKCS12
    keyAlias: tomcat
  error:
    include-message: always
